/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { GameDeveloper } from "./gameDeveloper";
import type { GamePlatform } from "./gamePlatform";
import type { GameGenre } from "./gameGenre";
import type { GamePublisher } from "./gamePublisher";

export interface AddOrUpdateGameDTO {
  id?: string;
  /** @minLength 1 */
  name: string;
  releaseDate?: string;
  /** @minLength 1 */
  description: string;
  /** @nullable */
  shortDescription?: string | null;
  gameDevelopers: GameDeveloper[];
  gamePlatforms: GamePlatform[];
  gameGenres: GameGenre[];
  /** @nullable */
  gamePublishers?: GamePublisher[] | null;
}
