/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface AddOrUpdatePlatformDTO {
  id?: string;
  /** @nullable */
  name?: string | null;
}
