/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { EPaymentType } from "./ePaymentType";

export interface AddorUpdatePaymentMethodDto {
  /** @nullable */
  payer?: string | null;
  /** @nullable */
  email?: string | null;
  type?: EPaymentType;
  /** @nullable */
  cardHolderName?: string | null;
  /** @nullable */
  cardNumber?: number | null;
}
