/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface AddOrUpdateReviewDTO {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  review?: string | null;
  /**
   * @minLength 0
   * @maxLength 5
   */
  rating?: number;
  userId?: string;
  productId?: string;
}
