/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface CompanyViewModel {
  id?: string;
  /** @nullable */
  name?: string | null;
  founded?: string;
  /** @nullable */
  logoPath?: string | null;
  /** @nullable */
  readonly developedGames?: readonly unknown[] | null;
  /** @nullable */
  readonly publishedGames?: readonly unknown[] | null;
}
