/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Nonconformity } from "./nonconformity";
import type { GameDeveloper } from "./gameDeveloper";
import type { GamePublisher } from "./gamePublisher";

export interface Company {
  /** @nullable */
  readonly nonconformities?: readonly Nonconformity[] | null;
  readonly isInvalid?: boolean;
  readonly isValid?: boolean;
  id?: string;
  readonly createdDate?: string;
  readonly lastUpdated?: string;
  readonly active?: boolean;
  /** @nullable */
  name?: string | null;
  founded?: string;
  /** @nullable */
  readonly logoPath?: string | null;
  /** @nullable */
  readonly gameDevelopers?: readonly GameDeveloper[] | null;
  /** @nullable */
  readonly gamePublishers?: readonly GamePublisher[] | null;
}
