/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export type EPaymentType = (typeof EPaymentType)[keyof typeof EPaymentType];

export const EPaymentType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
