/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Game } from "./game";
import type { Platform } from "./platform";

export interface GamePlatform {
  gameId?: string;
  game?: Game;
  platformId?: string;
  platform?: Platform;
}
