/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface GameViewModel {
  id?: string;
  /** @nullable */
  name?: string | null;
  releaseDate?: string;
  userScore?: number;
  price?: number;

  availableQuantity: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  imageRelativePath?: string | null;
  /** @nullable */
  coverImageRelativePath?: string | null;
  /** @nullable */
  readonly developers?: readonly unknown[] | null;
  /** @nullable */
  readonly genres?: readonly unknown[] | null;
  /** @nullable */
  readonly publishers?: readonly unknown[] | null;
  /** @nullable */
  readonly platforms?: readonly unknown[] | null;
}
