/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface GameListViewModel {
  id?: string;
  /** @nullable */
  name?: string | null;
  releaseDate?: string;
  /** @nullable */
  usersScore?: number | null;
  /** @nullable */
  price?: number | null;
  availableQuantity?: number;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  imageRelativePath?: string | null;
  /** @nullable */
  coverImageRelativePath?: string | null;
}
