/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Nonconformity } from "./nonconformity";
import type { EDepartment } from "./eDepartment";
import type { Review } from "./review";
import type { GamePlatform } from "./gamePlatform";
import type { GameGenre } from "./gameGenre";
import type { GameDeveloper } from "./gameDeveloper";
import type { GamePublisher } from "./gamePublisher";

export interface Game {
  /** @nullable */
  readonly nonconformities?: readonly Nonconformity[] | null;
  readonly isInvalid?: boolean;
  readonly isValid?: boolean;
  id?: string;
  readonly createdDate?: string;
  readonly lastUpdated?: string;
  readonly active?: boolean;
  /** @nullable */
  name?: string | null;
  department?: EDepartment;
  price?: number;
  totalQuantity?: number;
  availableQuantity?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  readonly imageRelativePath?: string | null;
  /** @nullable */
  readonly reviews?: readonly Review[] | null;
  /** @nullable */
  usersScore?: number | null;
  releaseDate?: string;
  /** @nullable */
  readonly coverImageRelativePath?: string | null;
  /** @nullable */
  readonly gamePlatforms?: readonly GamePlatform[] | null;
  /** @nullable */
  readonly gameGenres?: readonly GameGenre[] | null;
  /** @nullable */
  readonly gameDevelopers?: readonly GameDeveloper[] | null;
  /** @nullable */
  readonly gamePublishers?: readonly GamePublisher[] | null;
}
