/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Game } from "./game";
import type { Company } from "./company";

export interface GamePublisher {
  gameId?: string;
  game?: Game;
  publisherId?: string;
  publisher?: Company;
}
