/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Game } from "./game";
import type { Genre } from "./genre";

export interface GameGenre {
  gameId?: string;
  game?: Game;
  genreId?: string;
  genre?: Genre;
}
