/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Nonconformity } from "./nonconformity";
import type { GameGenre } from "./gameGenre";

export interface Genre {
  /** @nullable */
  readonly nonconformities?: readonly Nonconformity[] | null;
  readonly isInvalid?: boolean;
  readonly isValid?: boolean;
  id?: string;
  readonly createdDate?: string;
  readonly lastUpdated?: string;
  readonly active?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  readonly description?: string | null;
  /** @nullable */
  readonly gameGenres?: readonly GameGenre[] | null;
}
