/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export type GetApiGamesParams = {
  PageNumber?: number;
  PageSize?: number;
  SearchTerm?: string;
  SortBy?: string;
  IsDescending?: boolean;
  GenreId?: string;
  DeveloperId?: string;
  PlatformId?: string;
};
