/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export type GetApiAccountPasswordResetCheckTokenParams = {
  email?: string;
  token?: string;
};
