/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface LoginDto {
  /** @minLength 1 */
  userName: string;
  /** @minLength 1 */
  password: string;
}
