/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface NewPasswordDto {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  token: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  newPassword: string;
  /** @minLength 1 */
  confirmPassword: string;
}
