/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface Nonconformity {
  /** @nullable */
  readonly nonconformities?: readonly Nonconformity[] | null;
  readonly isInvalid?: boolean;
  readonly isValid?: boolean;
  /** @nullable */
  property?: string | null;
  /** @nullable */
  message?: string | null;
}
