/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export type PutApiGamesIdUploadthumbimageBody = {
  /** The image file to upload */
  file: Blob;
};
