/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */

export interface RegisterDto {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  userName: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
}
