/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { Nonconformity } from "./nonconformity";
import type { Product } from "./product";

export interface Review {
  /** @nullable */
  readonly nonconformities?: readonly Nonconformity[] | null;
  readonly isInvalid?: boolean;
  readonly isValid?: boolean;
  id?: string;
  readonly createdDate?: string;
  readonly lastUpdated?: string;
  readonly active?: boolean;
  /** @nullable */
  readonly considerations?: string | null;
  userId?: string;
  rating?: number;
  productId?: string;
  product?: Product;
}
