/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Sahib Game Store
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from "./orderStatus";

export interface UpdateOrderDto {
  /** @nullable */
  address?: string | null;
  status?: OrderStatus;
}
